default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: slim-blog_development

test:
  <<: *default
  database: slim-blog_test

production:
  <<: *default
  database: slim-blog_production
  username: slim-blog
  password: <%= ENV['BLOG_DATABASE_PASSWORD'] %>
